### PR TITLE
Fix to make the psiphon test run

### PR DESCRIPTION
**Pull request by hellais**
* Remove unneeded imports

### CODE REVIEW

**Comment by hellais** [comment]
@juga0 @srvetus

Some changes need to happen on the psiphon test to make it work.

The following is missing:

* [ ] It should set the `success` key to the result of the run of psiphon (that is was it able to fetch the website in question)

* [ ] The structure of the `ProcessTest` template should change to reduce the amount of nesting. It should look more like something like this:
```
            'command_name': command_name
            'command_stdout': result['stdout'],
            'command_stderr': result['stderr'],
            'command_exit_reason': result['exit_reason']
```

* [ ] The install scripts is not installing properly all the required dependencies @anadahz says

**Comment by anadahz** [comment]
@juga0
Extensive test report: #448.

**Comment by juga0** [comment]
@hellais 
> It should set the success key to the result of the run of psiphon (that is was it able to fetch the website in question)

self.report['success'] = False was initially in the code https://github.com/juga0/ooni-probe/commit/a16118648a8604775bad06af814a86ca4d95a852#diff-5c5dfaf17ce0881da1f4f8016843c1d6R103, but after changing the code to inherit from HTTPTest was lost. I'm not sure where to add it in the current code without modifying HTTPTest.

**Comment by juga0** [comment]
@hellais 
> The structure of the ProcessTest template should change to reduce the amount of nesting. 

There is not nesting for the two keys that this test add (psiphon_installed and success). The nesting after the command and the requests happen because of inheriting from ProcessTest and HTTPTest. 
I thought that was the desired output format, and was already accepted in the specs (https://github.com/TheTorProject/ooni-spec/commit/c9be501c39e65bb98a3640be6c7a67ed9ec911a8#diff-fae714cf60b035cce6f96fec2ace2eacR57).

**Comment by juga0** [comment]
@anadahz 
>  The install scripts is not installing properly all the required dependencies @anadahz says
Thanks for the report in https://github.com/TheTorProject/ooni-probe/issues/448, commenting about it there

**Comment by juga0** [comment]
There is a different major problem with the test right now.
When psiphon fails (for instance, missing some dependency), the test does not execute doRequest and stdout variable contains the error, but then ooni retry the test and for some reason doRequest is executed, stdout error is lost nor is wroten in the report.
This might be a similar problem to the one with OpenVPN commented by srvetus in https://github.com/TheTorProject/ooni-probe/pull/411#issuecomment-163745309. Changing the timeout doesn't affect to the number of retries.
Is there a way to don't make ooni to retry the test?.

**Comment by hellais** [comment]
Why does OONI retry the test? It should only retry the test if either:

1) It times out because it's running too long

2) There is an un-handled exception that is not being handled properly in the test logic

**Comment by juga0** [comment]
2. The exception happens in the cleanup,  ProcessExitedAlready .Debug with extra logs:

[D] ProcessDirector: outReceived: STDOUT: Traceback (most recent call last):\r\n  File "/tmp/tmpApkfGU", line 2, in <module>\r\n    from psi_client import connect\r\n  File "/home/foo/psiphon-circumvention-system/pyclient/pyclient/psi_client.py", line 22, in <module>\r\n    from psi_ssh_connection import SSHConnection, OSSHConnection\r\n  File "/home/foo/psiphon-circumvention-system/pyclient/pyclient/psi_ssh_connection.py", line 21, in <module>\r\n
[D] ProcessDirector: shouldClose
[D] ProcessDirector: outReceived: STDOUT:     import pexpect\r\nImportError: No module named pexpect\r\n
[D] ProcessDirector: shouldClose
[D] ProcessDirector: processExited [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 1.\n]
[D] ProcessDirector: processEnded [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 1.\n]
[D] ProcessDirector: finish
[D] ProcessTest: Finished ['/home/user/.virtualenvs/ooniprobedev/bin/python', '/tmp/tmpApkfGU']: {'exit_reason': 'process_done', 'stderr': '', 'stdout': 'Traceback (most recent call last):\\r\\n  File "/tmp/tmpApkfGU", line 2, in <module>\\r\\n    from psi_client import connect\\r\\n  File "/home/foo/psiphon-circumvention-system/pyclient/pyclient/psi_client.py", line 22, in <module>\\r\\n    from psi_ssh_connection import SSHConnection, OSSHConnection\\r\\n  File "/home/foo/psiphon-circumvention-system/pyclient/pyclient/psi_ssh_connection.py", line 21, in <module>\\r\\n    import pexpect\\r\\nImportError: No module named pexpect\\r\\n'}
[D] !!!ProcessTest.processEnded, writing to report command results


[D] ProcessDirector: close
[D] PsiphonTest:cleanup
[D] Task <ooni.tasks.Measurement object at 0xb6665dec> has failed 2 times
Traceback (most recent call last):
  File "/home/user/.virtualenvs/ooniprobedev/local/lib/python2.7/site-packages/ooniprobe-1.3.1-py2.7.egg/ooni/tasks.py", line 77, in _timedOut
    self._running.cancel()
  File "/home/user/.virtualenvs/ooniprobedev/local/lib/python2.7/site-packages/Twisted-14.0.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 467, in cancel
    self.errback(failure.Failure(CancelledError()))
  File "/home/user/.virtualenvs/ooniprobedev/local/lib/python2.7/site-packages/Twisted-14.0.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 423, in errback
    self._startRunCallbacks(fail)
  File "/home/user/.virtualenvs/ooniprobedev/local/lib/python2.7/site-packages/Twisted-14.0.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/user/.virtualenvs/ooniprobedev/local/lib/python2.7/site-packages/Twisted-14.0.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "ooni/nettests/third_party/psiphon_works.py", line 137, in cleanup
    self.processDirector.transport.signalProcess('INT')
  File "/home/user/.virtualenvs/ooniprobedev/local/lib/python2.7/site-packages/Twisted-14.0.0-py2.7-linux-i686.egg/twisted/internet/process.py", line 339, in signalProcess
    raise ProcessExitedAlready()
twisted.internet.error.ProcessExitedAlready: 
[D] Rescheduling...

This test was supposed to be minimal an check if psiphon is found ("psiphon_installed" should be renamed to  "psiphon_found") and try an HTTP request, not to check other reasons why psiphon wouldn't run.
A way to report why psiphon did not run properly and write success = false in the report is to add in cleanup:

            try:
                self.processDirector.transport.signalProcess('INT')
            except ProcessExitedAlready:
                self.report['success'] = false

**Comment by juga0** [comment]
@hellais @anadahz could you check if now:
1. Psiphon is installed propertly with PR https://github.com/TheTorProject/ooni-probe/pull/452
2. Psiphon is running properly with PR https://github.com/TheTorProject/ooni-probe/pull/451 in this 3 cases:
   a. Psiphon is not found because not cloned or wrong path (path can be provided with -p)
   b. Psiphon fails to run (for instance, pexpect dependency not installed)
   c. HTTP request fails (for instance, wrong url provided with -u)
?

**Comment by juga0** [comment]
Until here, the test logic is:

1. psiphon path is not found: psiphon_installed=false, success=null
2. psiphon path is found but psiphon fails to run for whatever reason: psiphon_installed=true, success=null
3. psiphon runs but the request fail: psiphon_installed=true, success=true

At this stage the test accomplish with the requirements stated in https://trac.torproject.org/projects/tor/ticket/16911:
 The test must:
    execute the Psiphon 3 client command
    check that the output text of the command match the expected output text
    check that is possible to make an HTTP request using the Psiphon3 SOCKS proxy

However, in a conversation with @hellais, new changes are requested:

> I would make two keys
> bootstrapped_success: BOOL
>  that is true if you find that text
>  false if you don't find that text
> request_success: BOOL
> that is true or false if you are able or not to perform the HTTP request 

The commit https://github.com/juga0/ooni-probe/commit/c9d1d950e76ccba69a3b7373b99e26be4b679ee9 makes those changes

**Comment by anadahz** [comment]
Running the psiphon test [install script](https://github.com/juga0/ooni-probe/commit/16bb4478c33ee80bff9a364e950ee98818129a4d)

Then running the psiphon test:
```
# ooniprobe -ng ooni-probe/ooni/nettests/third_party/psiphon.py
```
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
Not reporting using a collector
[D] No test deck detected
[D] UsageOptions
[D] UsageOptions
You should add annotations for the country, city and ASN
Fetching required net test inputs...
[D] Fetching and verifying inputs
Looking up collector and test helpers
[D] Creating /root/report-psiphon_test-2016-01-11T191503Z.yamloo
[D] Writing report with YAML reporter
[D] Starting this task <generator object generateMeasurements at 0x7fe4aaddef00>
[D] Running <class 'psiphon.PsiphonTest'> test_psiphon
[D] PiphonTest._setUp: setting socksproxy
[D] Finished test setup
[D] PsiphonTest.setUp
[D] psiphon path: /root/psiphon-circumvention-system/pyclient/pyclient
[D] command: /usr/bin/python/tmp/tmp985zrZ
[D] PsiphonTest.test_psiphon
[!] psiphon path does not exists, is it installed?
[D] Adding {'request_success': None, 'socksproxy': '127.0.0.1:1080', 'test_start_time': 1452546903.0, 'agent': 'agent', 'bootstrapped_success': None, 'input': None, 'psiphon_found': False} to report
[D] Checking all tasks for completion 0 == 1
[D] Successfully completed measurement: <ooni.tasks.Measurement object at 0x7fe4aa4dbe10>
[D] Starting this task <ooni.tasks.ReportEntry object at 0x7fe4ab1b6bd0>
[D] Writing report with YAML reporter
[D] Successfully performed report <ooni.tasks.ReportEntry object at 0x7fe4ab1b6bd0>
[D] None
[D] Checking all tasks for completion 1 == 1
Report ID: UbR3NDLd6u3VNi8ETgOaMhcNySMDvMoSeFdMz8WMxXseAPagpQVpPzfSoPTWZvaH                   
[D] Successfully performed measurement <ooni.tasks.Measurement object at 0x7fe4aa4dbe10>
[D] None
Main loop terminated.
```
it seems that psiphon is not properly installed or something is wrong with the hardcoded path?

**Comment by hellais** [comment]
@anadahz you need to run it by specifying the path to the psiphon executable pyclient directory like so: `./bin/ooniprobe-dev -n ooni/nettests/third_party/psiphon.py -u http://google.com/ -p /root/psiphon-circumvention-system/pyclient/`

**Pull request merged**
