### PR TITLE
Feature/install

### PR DESCRIPTION
**Pull request by hellais**
This adds an `install.sh` script to replace the `setup-dependencies.sh` script.

### CODE REVIEW

**Comment by hellais** [comment]
Can we merge this?

**Comment by anadahz** [comment]
Check https://github.com/TheTorProject/ooni-probe/pull/404

**Comment by hellais** [comment]
I did and commented on it.

That PR you openned is a pull request that is requesting to merge your branch (`fix/feature/install-script`) into this branch (`feature/install`).
You need to first merge this in order to then merge this one.

Also in general it's best to always to PR onto master instead of into another non merged branch.

**Comment by anadahz** [comment]
I would like to first test thoroughly the install script before merging it to master

**Comment by hellais** [comment]
@anadahz can you confirm that now this does indeed work properly? If so could you please merge it?

**Comment by anadahz** [comment]
Looks good to me.
We should proceed by merging it.

**Pull request merged**
