### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by meejah**

### CODE REVIEW

**Comment by bassosimone** [comment]
I see that the build fails for Twisted < 15 with this error:

```
pkg_resources.UnknownExtra: Twisted 13.2.0 has no such extra feature 'tls'
```

I don't think this has anything to do with this diff, however.

I'll check whether this error was happening also before.

**Comment by bassosimone** [comment]
Hmm, this [recent build of master](https://travis-ci.org/TheTorProject/ooni-probe/builds/219617541) did not fail like this. I guess I'll leave the merge to @hellais.

**Comment by hellais** [comment]
I suspect the issue with:

```
pkg_resources.UnknownExtra: Twisted 13.2.0 has no such extra feature 'tls'
```
Is due to txtorcon specifying the Twisted dependency as: https://github.com/meejah/txtorcon/blob/master/requirements.txt#L4

**Comment by hellais** [comment]
The build will be fixed once https://github.com/TheTorProject/ooni-probe/pull/752/commits/ef827094060e56808ebb69cd1bb69ba24c6ca458 is merged.

**Comment by hellais** [comment]
This is good to be merged. Thanks for this! 👍

**Pull request merged**
