### PR TITLE
OONI Control Interface

### PR DESCRIPTION
**Pull request by 0xPoly**
Specification for controlling ooniprobe through JSON messages over HTML

### CODE REVIEW

**Comment by 0xPoly** [comment]
Yes, I should've squashed before pushing...

**Comment by hellais** [comment]
heheh, can you perhaps rebase and force push?

**Comment by bassosimone** [comment]
Squashing manually is not necessary anymore! now GitHub has this cool option that instead of merging the traditional way you could squash all commits into a single commit and that apply it on master :-).

**Comment by bassosimone** [comment]
(afaik, you still need to manually perform rebase, though.)

**Comment by 0xPoly** [comment]
Done :)

**Comment by hellais** [comment]
LGTM!

**Pull request merged**
