### PR TITLE
Fix indentation of torrc option

### PR DESCRIPTION
**Pull request by anadahz**

### CODE REVIEW

**Comment by hellais** [comment]
Actually the `torrc` key needs to be nested inside of `tor`:

https://github.com/TheTorProject/ooni-probe/blob/960e52a95b446af73be8e4152f415aa804ab9fe1/ooni/director.py#L374

**Comment by anadahz** [comment]
`ooniprobe -f ooniprobe.conf blocking/http_requests --url http://www.thetorproject.com`
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/bin/ooniprobe", line 4, in <module>
    __import__('pkg_resources').run_script('ooniprobe===1.5.0-master', 'ooniprobe')
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/user/ooni-probe/ooni-env/lib/python2.7/site-packages/ooniprobe-1.5.0_master-py2.7.egg/EGG-INFO/scripts/ooniprobe", line 12, in <module>
    check_incoherences=True)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0_master-py2.7.egg/ooni/oonicli.py", line 186, in setupGlobalOptions
    config.read_config_file(check_incoherences=check_incoherences)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0_master-py2.7.egg/ooni/settings.py", line 163, in read_config_file
    configuration = yaml.safe_load(config_file_contents)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<string>", line 119, column 5:
                 UseBridges 1
```
Contents of `ooniprobe.conf`:
```
# This is the configuration file for OONIProbe
# This file follows the YAML markup format: http://yaml.org/spec/1.2/spec.html
# Keep in mind that indentation matters.

basic:
    # Where OONIProbe should be writing it's log file
    logfile: /home/user/.ooni/ooniprobe.log
privacy:
    # Should we include the IP address of the probe in the report?
    includeip: false
    # Should we include the ASN of the probe in the report?
    includeasn: true
    # Should we include the country as reported by GeoIP in the report?
    includecountry: true
    # Should we include the city as reported by GeoIP in the report?
    includecity: false
    # Should we collect a full packet capture on the client?
    includepcap: false
reports:
    # This is a prefix for each packet capture file (.pcap) per test:
    pcap: null
    collector: null
advanced:
    geoip_data_dir: /home/user/ooni-probe/ooni-env/share/GeoIP
    debug: true
    # enable if auto detection fails
    #tor_binary: /usr/sbin/tor
    #obfsproxy_binary: /usr/bin/obfsproxy 
    # For auto detection
    interface: auto
    # Of specify a specific interface
    #interface: wlan0
    # If you do not specify start_tor, you will have to have Tor running and
    # explicitly set the control port and SOCKS port
    start_tor: true
    # After how many seconds we should give up on a particular measurement
    measurement_timeout: 60
    # After how many retries we should give up on a measurement
    measurement_retries: 4
    # How many measurements to perform concurrently
    measurement_concurrency: 6
    #measurement_concurrency: 10
    # After how may seconds we should give up reporting
    reporting_timeout: 80
    # After how many retries to give up on reporting
    reporting_retries: 3
    # How many reports to perform concurrently
    reporting_concurrency: 15
    oonid_api_port: 8042
tor:
    #socks_port: 9050
    #control_port: 8802
    # Specify the absolute path to the Tor bridges to use for testing
    #bridges: bridges.list
    # Specify path of the tor datadirectory.
    # This should be set to something to avoid having Tor download each time
    # the descriptors and consensus data.
    #data_dir: ~/.tor/
    torrc:
         UseBridges 1
         Bridge meeklite 0.0.2.0:1 url=https://meek-reflect.appspot.com/ front=www.google.com
         Bridge meeklite 0.0.2.0:2 url=https://d2zfqthxsdq309.cloudfront.net/ front=a0.awsstatic.com
         Bridge meeklite 0.0.2.0:3 url=https://az786092.vo.msecnd.net/ front=ajax.aspnetcdn.com
         ClientTransportPlugin meeklite exec /usr/bin/obfs4proxy --log meek-client.log
```
-------------------
Replacing tabs with spaces below `torrc` option:
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
[D] No test deck detected
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
Starting Tor...
[!] Could not start the director
[!] An unhandled exception occurred while starting the director!
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/lib/python2.7/site-packages/ooniprobe-1.5.0_master-py2.7.egg/EGG-INFO/scripts/ooniprobe", line 16, in <module>
    d = runWithDirector(global_options)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0_master-py2.7.egg/ooni/oonicli.py", line 400, in runWithDirector
    global_options=global_options)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0_master-py2.7.egg/ooni/oonicli.py", line 305, in runTestWithDirector
    check_incoherences=global_options['check_incoherences'])
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0_master-py2.7.egg/ooni/director.py", line 134, in start
    yield self.startTor()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0_master-py2.7.egg/ooni/director.py", line 375, in startTor
    for i in config.tor.torrc.keys():
exceptions.AttributeError: 'str' object has no attribute 'keys'
```

**Comment by hellais** [comment]
This is because you are not formatting the keys inside of torrc as valid YAML.

Try replacing:

```
         UseBridges 1
         Bridge meeklite 0.0.2.0:1 url=https://meek-reflect.appspot.com/ front=www.google.com
         Bridge meeklite 0.0.2.0:2 url=https://d2zfqthxsdq309.cloudfront.net/ front=a0.awsstatic.com
         Bridge meeklite 0.0.2.0:3 url=https://az786092.vo.msecnd.net/ front=ajax.aspnetcdn.com
         ClientTransportPlugin meeklite exec /usr/bin/obfs4proxy --log meek-client.log
```

With

```
         UseBridges: 1
         Bridge: meeklite 0.0.2.0:1 url=https://meek-reflect.appspot.com/ front=www.google.com
         Bridge: meeklite 0.0.2.0:2 url=https://d2zfqthxsdq309.cloudfront.net/ front=a0.awsstatic.com
         Bridge: meeklite 0.0.2.0:3 url=https://az786092.vo.msecnd.net/ front=ajax.aspnetcdn.com
         ClientTransportPlugin: meeklite exec /usr/bin/obfs4proxy --log meek-client.log
```

**Comment by anadahz** [comment]
It seems that tor cannot be bootstrapped using the keyed format:
```
Log opened.
[D] No test deck detected
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
Starting Tor...
[D] Setting control port as 3409
[D] Setting SOCKS port as 35702
Spawning tor process with DataDirectory /tmp/tortmpYZZfZ_
5%: Connecting to directory server
5%: Connecting to directory server
```
The directory `/tmp/tortmpYZZfZ_` dosn't have any cached-certs or cached-microdesc-consensus files.
Using the non-keyed format bootstraps tor successfully.

Are you able to bootstrap tor in ooniprobe with your example configuration?

**Comment by hellais** [comment]
Ha, I think I know what is happening.

The keys below the first one are being shadowed by the first key that is the meek pluggable that is currently offline due to google having deactivated the gapps account.

They should actually be listed a list:

```
Bridge:
- meeklite 0.0.2.0:1 url=https://meek-reflect.appspot.com/ front=www.google.com
- meeklite 0.0.2.0:3 url=https://az786092.vo.msecnd.net/ front=ajax.aspnetcdn.com
etc.
```

If you don't put them nested in the tor key it just will ignore them.

**Comment by anadahz** [comment]
Still is not being parsed correctly:
```
  File
  "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/yaml/scanner.py",
  line 257, in fetch_more_tokens
      % ch.encode('utf-8'), self.get_mark())
      yaml.scanner.ScannerError: while scanning for the next token
      found character '\t' that cannot start any token
        in "<string>", line 143, column 1:
                 - meeklite 0.0.2.0:1 url=https ... 
```
As I mentioned I was able to connect with my example configuration, I also tried tor client and I was able to connect via meek.
Just realized in the example config above it's should be meek_lite and not meeklite.
When you test it take care to properly use the meek client binary PATH, for instance if you use obfs4proxy (meek_lite) or meek-client.

**Comment by hellais** [comment]
Again that's a YAML parsing error. You probably need to enclose the list inside of quotes: `"`.

Here is how my config looks like for obfs3:

```
tor:
    torrc:
        UseBridges: 1
        Bridge:
        - "obfs3 194.132.208.71:25504 C33A2AFE9827513057D478399589BB1675C0355A"
        - "obfs3 194.132.208.58:58630 F941CF22D19039780D77CCDC86F2D48116179D4C"
        - "obfs3 23.252.105.31:3443 CDAE9FD7710761D1914182F62B1B47F2FBF1FDE1"
        ClientTransportPlugin: "obfs3 exec /path/to/obfsproxy managed"
```

**Comment by anadahz** [comment]
I haven't figure out yet what should be the proper format.
If you happen to find out just mention it here and I could add it in the documentation.

**Comment by hellais** [comment]
[see](https://github.com/TheTorProject/ooni-probe/pull/510#issuecomment-220803836)

**Comment by anadahz** [comment]
Rephrasing better:
I haven't figure out yet how one can use meek with ooniprobe.
When you figure out the exact indentation in order to use meek PT in ooniprobe please provide an update here so that I can add it to the documentation and as an example to the `ooniprobe.conf`.
@hellais I hope is clear now.

**Comment by hellais** [comment]
The exact indentation is in [here](https://github.com/TheTorProject/ooni-probe/pull/510#issuecomment-220803836). Just replace `obfs3` with `meeklite` or whatever is the pluggable transport you want to use.

**Comment by anadahz** [comment]
config excerpt:
```
tor:
    torrc:
        UseBridges: 1
        Bridge:
        - "meek_lite 0.0.2.0:1 url=https://meek-reflect.appspot.com/ front=www.google.com"
        - "meek_lite 0.0.2.0:2 url=https://d2zfqthxsdq309.cloudfront.net/ front=a0.awsstatic.com"
        - "meek_lite 0.0.2.0:3 url=https://az786092.vo.msecnd.net/ front=ajax.aspnetcdn.com"
        ClientTransportPlugin: "meek_lite exec /usr/bin/obfs4proxy"
```
Error msg:
```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<string>", line 105, column 1:
        Bridge:
    ^
```

**Comment by bassosimone** [comment]
@anadahz afaik, tabs should not appear in YAML files; try replacing them with spaces!

**Comment by anadahz** [comment]
@bassosimone you are right, sorry for my confusion.
I guess it makes sense to add an example of the Bridge YAML format  in `ooniprobe.conf.sample`

**Comment by hellais** [comment]
LGTM!

**Pull request merged**
