### PR TITLE
The version number in master should always be greater than the latest…

### PR DESCRIPTION
**Pull request by hellais**
… release

This is to allow us to distinguish reports that are run from ooniprobe versions
cloned from master and those run from packages.

### CODE REVIEW

**Comment by bassosimone** [comment]
Looks good to me! Will merge as soon as automatic checks complete!

**Comment by bassosimone** [comment]
@hellais, I don't immediately understand how, but [this diff is breaking the build](https://travis-ci.org/TheTorProject/ooni-probe/jobs/131115723#L1783).

**Comment by bassosimone** [comment]
Ah, right! Guess I've figured it out, probably the issue is that it tries to download ooni resources from github using a version number that does not exist yet.

**Comment by hellais** [comment]
Yes you are right.

I came up with this solution that is a bit dirty and requires a slight bit more of hassle when doing a new release, but I can't think of something better for the moment.

**Comment by bassosimone** [comment]
> I came up with this solution that is a bit dirty and requires a slight bit more of hassle when doing a new release, but I can't think of something better for the moment.

Yeah, for now it would do! Merging!

**Pull request merged**
