### PR TITLE
Add psiphon install script

### PR DESCRIPTION
**Pull request by bassosimone**
Discussed with @anadahz. This is equal to the script in juga0/ooni-probe (checked this with git diff) except that it was rebased with respect to master.

### CODE REVIEW

**Comment by hellais** [comment]
@anadahz can you take care of this?

**Comment by anadahz** [comment]
I made some trivial changes to the install script.
@juga0 @bassosimone please check it.

**Comment by juga0** [comment]
check it, works, thanks

**Comment by anadahz** [comment]
Indeed this is ready to merge @bassosimone 
Thanks!

**Comment by hellais** [comment]
I will proceed in merging this then. Thank you all for the excellent work! :+1: :heart:

**Pull request merged**
