### PR TITLE
Fix Microsoft Azure meek endpoint, format

### PR DESCRIPTION
**Pull request by anadahz**
The default azure meek endpoint was [changed some months ago](https://gitweb.torproject.org/builders/tor-browser-bundle.git/commit/Bundle-Data/PTConfigs/bridge_prefs.js?id=92c82fb6b5aa06c9ed4c304d47aca1bf3e92d1ca).

Due to the meek azure endpoint change the reports of the `meek_fronted_requests` test are reporting  a lot of false positives. An example of a `meek_fronted_requests` [test false positive report](https://explorer.ooni.torproject.org/measurement/20170328T004744Z_AS209_zG9K5kcKg3GAv7auTTuUsNWIv03OH1vje8NhvSf8I7Gzc7Ga7S?input=%5Bu%27ajax.aspnetcdn.com%27,%20u%27az668014.vo.msecnd.net%27%5D)

### CODE REVIEW

**Comment by anadahz** [comment]
What is needed for this to get merged into master?
By using outdated meek bridges we are influencing with a lot of false positives the meek reports in OONI data.

**Comment by hellais** [comment]
It would be good to mention in the commit or even just here a reference to why and where the endpoints changed with an authoritative source.

Also it should be rebased into master and the CI should pass.

**Comment by anadahz** [comment]
> It would be good to mention in the commit or even just here a reference to why and where the endpoints changed with an authoritative source.

Indeed it will be good, do you want me to add a commit and add a reference on this, or this can be merged now?

**Comment by hellais** [comment]
> Indeed it will be good, do you want me to add a commit and add a reference on this, or this can be merged now

yeah just push to this branch and then I will merge it.

**Comment by anadahz** [comment]
bump

**Pull request merged**
