### PR TITLE
Fix/twisted15.0

### PR DESCRIPTION
**Pull request by hellais**

### CODE REVIEW

**Comment by hellais** [comment]
@anadahz can you confirm this works properly? If so could you merge it?

**Comment by anadahz** [comment]
This is what I get (see below on how to reproduce this):
```
 [-] Performing GET request to http://adium.im over Tor
 [-] The two body lengths appear to match
 [-] censorship is probably not happening
 [-] Unhandled error in Deferred:
 [-] Unhandled Error
        Traceback (most recent call last):
          File "ooniprobe-PR401-twisted15/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "ooniprobe-PR401-twisted15/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 859, in _cbDeferred
            self.callback(self.resultList)
          File "ooniprobe-PR401-twisted15/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
            self._startRunCallbacks(result)
          File "ooniprobe-PR401-twisted15/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "ooniprobe-PR401-twisted15/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "ooniprobe-PR401-twisted15/local/lib/python2.7/site-packages/ooniprobe-1.3.1-py2.7.egg/ooni/nettests/blocking/http_requests.py", line 141, in postProcessor
            experiment.headers)
          File "ooniprobe-PR401-twisted15/local/lib/python2.7/site-packages/ooniprobe-1.3.1-py2.7.egg/ooni/nettests/blocking/http_requests.py", line 95, in compare_headers
            diff = headers_a.getDiff(headers_b)
        exceptions.AttributeError: 'Headers' object has no attribute 'getDiff'

 [-] Performing GET request to http://adium.im
```
To reproduce this warning:
```shell
mkvirtualenv ooniprobe-PR401-twisted15
source ooniprobe-PR401-twisted15/bin/activate
git clone https://github.com/TheTorProject/ooni-probe.git ooni-probe-PR401
cd ooni-probe-PR401 && git checkout fix/twisted15.0
pip install -r requirements.txt
python setup.py install
oonideckgen
ooniprobe -i 0.1.0-it-user.deck
```

**Comment by hellais** [comment]
@bassosimone can you check this out since it fixes the build?

**Comment by bassosimone** [comment]
@hellais ok, adding this to TODO list

**Comment by bassosimone** [comment]
The diff looks good to me. I am currently testing this branch.

**Comment by bassosimone** [comment]
I have run a few tcp_connect tests and most of them worked (in a couple of cases it was not possible to reach out to the collector). Afterwards, I created a deck and run ooniprobe using that deck. It has been running for 30 minutes now performing both normal and torified requests. Let's merge!

**Comment by bassosimone** [comment]
Forgot to say: of course I was in a virtual environment created from scratch where:

```
>>> import twisted
>>> twisted.__version__
'15.4.0'
```

**Comment by bassosimone** [comment]
FTR, I am also investigating the issue report by @anadahz above and testing a diff to fix it.

**Comment by bassosimone** [comment]
Created #424 to address the warning reported by @anadahz.

**Pull request merged**
