### PR TITLE
Feature/cloud fronted collectors

### PR DESCRIPTION
**Pull request by hellais**
This is still WIP and not yet ready for merging.

But I am going to use this to keep track of the changes.

Note: This depends on #540.

### CODE REVIEW

**Comment by hellais** [comment]
This branch is now ready to be reviewed and tested!

I bumped the version number up as I would like to cut a release candidate before making the proper release. This release candidate has in it the https and cloudfronted bouncer of the testing machine.

**Comment by hellais** [comment]
* [ ] Add command line option for specifying the `preferred_backend`

**Comment by hellais** [comment]
Added option to specify the preferred-backend.

**Comment by anadahz** [comment]
Thank you for your excellent work @hellais !
I haven't found any issues after extended testing of this PR.

Please proceed by merging this.

**Comment by hellais** [comment]
Excellent, thanks a bunch!

**Pull request merged**
